from typing import Any, Protocol

from sqlalchemy import Result


class RepositorySession(Protocol):
    def add(self, instance: Any) -> None: ...
    def delete(self, instance: Any) -> None: ...
    def get(self, entity: Any, ident: Any) -> Any: ...
    def execute(self, statement: Any) -> Result[Any]: ...
    def flush(self) -> None: ...
    def scalar(self, statement: Any) -> Any: ...
    def scalars(self, statement: Any) -> Any: ...
